### ISSUE TITLE
アンケート集計アプリ提出

### ISSUE THREAD

**Issue by GS03-35-HikasaOsamu** [GS03-35-HikasaOsamu/kadai#2]

**Comment by gs-teacher** [comment]
レビュー担当の増子です。

全体的に問題ないようですが、出力に`print`を使っているとことと`echo`を使っているところがありました。どちらでも問題はありませんが、どちらかに統一したほうがよいと思います。
現場ではecho派が多い気がします(結果を返さないため若干早いという噂もありますが)

**Comment by GS03-35-HikasaOsamu** [comment]
レビューありがとうございます。echo に統一しました。

**Comment by gs-teacher** [comment]
:+1:
