### ISSUE TITLE
第7回課題を提出します。

### ISSUE THREAD

**Issue by GS03-35-HikasaOsamu** [GS03-35-HikasaOsamu/kadai#3]
よろしくお願いいたします。

**Comment by gs-teacher** [comment]
レビュー担当の増子です。
ご連絡ありがとうございます。

全体的にPHPの書き方は慣れているようなので、問題ありません！
PDOなども使えていると思います。
ちょっと細かいですが、気になる点を挙げます。

* idが数字から始まっている
これは調べてみてわかったのですが、id="1"などの数字だけのものはHTML構文としてはOKですが、CSSやJSでは使えないので、アルファベットから始まるものを使用するべきです。
https://github.com/GS03-35-HikasaOsamu/kadai/blob/master/7/index.php#L28-L29

* 変数名などは意味のある名前をつけましょう
また、id="a"などは後で使用するときにも意味がわからないので、必要であれば名前をちゃんとつけてあげましょう。labelを貼りたいだけであれば、labelでinputとラベルのテキスト全体を囲うことで同じことができます。
https://github.com/GS03-35-HikasaOsamu/kadai/blob/master/7/index.php#L31-L35
こちらも同様に名前をつけてあげたほうが良いです。後でパラメータを追加したいとかなったときには混乱すると思います。
https://github.com/GS03-35-HikasaOsamu/kadai/blob/master/7/index.php#L28-L35

* codeという変数はどこにも定義されていないようですが、htmlでコメントされていたので消し忘れでしょうか？
https://github.com/GS03-35-HikasaOsamu/kadai/blob/master/7/login_check.php#L8

* カラムの型は適切なものを選択しましょう。
ageやsexなどはtextでも動きますが、何桁も入るものではないので、varcharya
charなどにしてあげたほうがよいです。
https://github.com/GS03-35-HikasaOsamu/kadai/blob/master/7/sql/gs_db.sql#L32-L33

**Comment by GS03-35-HikasaOsamu** [comment]
レビューありがとうございます。ご指摘いただきました箇所を修正しました。

**Comment by gs-teacher** [comment]
:+1: 
指摘した箇所が修正されていることを確認しました。
素早い対応すばらしい！

**Comment by GS03-35-HikasaOsamu** [comment]
ありがとうございます！
